services:
  macros-api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - web
  macros-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - macros-api
    networks:
      - web

networks:
  web:
    external: true